# Generated by Django 5.2.1 on 2025-06-26 06:54

import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_bio_author_github_author_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check this box to feature this post on the homepage.'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short summary of the post, displayed on the index page.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='blog_posts', to='blog.category'),
        ),
    ]
