# Generated by Django 5.2.1 on 2025-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_blogpostpage_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
