# Generated by Django 5.2.1 on 2025-06-04

import django.db.models.deletion
import uuid
from django.db import migrations, models


def assign_default_locale(apps, schema_editor):
    import uuid
    FormField = apps.get_model('base', 'FormField')
    Locale = apps.get_model('wagtailcore', 'Locale')
    
    try:
        default_locale = Locale.objects.get(language_code='en')
    except Locale.DoesNotExist:
        default_locale = Locale.objects.first()

    for field in FormField.objects.all():
        field.locale = default_locale
        field.translation_key = uuid.uuid4()  # Ensure uniqueness
        field.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subscriber'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={},
        ),
        migrations.AddField(
            model_name='formfield',
            name='locale',
            field=models.ForeignKey(
                to='wagtailcore.locale',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                verbose_name='locale',
                editable=False,
                null=True,  # TEMPORARILY allow null
            ),
        ),
        migrations.AddField(
            model_name='formfield',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(assign_default_locale),
        migrations.AlterField(
            model_name='formfield',
            name='locale',
            field=models.ForeignKey(
                to='wagtailcore.locale',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                verbose_name='locale',
                editable=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('translation_key', 'locale')},
        ),
    ]
