# Generated by Django 5.2.1 on 2025-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_formfield_options_formfield_locale_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'name')},
        ),
    ]
